### ISSUE TITLE
Copy field names

### ISSUE THREAD

**Issue by SteveDrakey** [MscrmTools/MsCrmTools.MetadataBrowser#1]
Lots of CRM systems have obscure names for fields, I find that when coding Copy and Paste reduces coding errors, it would be very nice if MetadataBrowser would allow COPY for field names / entity names etc.

**Comment by MscrmTools** [comment]
@SteveDrakey, you can already copy names or any other information from the properties panel for each entity/attribues and so on
Isn't it enough?

**Comment by DiggaTheWolf** [comment]
@MscrmTools Hi, the only thing I can copy/paste is on any of the property panels. Selecting a property name, this pastes the value only.

I would like to see all grids exportable or at least being able to copy/paste single/multiple records which includes the column headers too.

**Comment by MscrmTools** [comment]
What about using Metadata Document Generator to export all attributes in an excel spreadsheet?

**Comment by DiggaTheWolf** [comment]
That's fine if I wanted a complete reference, though if the data is displaying in a grid, then why can't I copy the data. An example would be the entity ObjectTypeCode. If I wanted to get this value for all entities, then I have to create a workbook with all entities just to get the entity summary list. It makes sense to me to allow copy/paste from any results grid rather than going through a cumbersome process.

**Comment by MscrmTools** [comment]
Ok so what is your expectation? Excel export? Right click and copy/paste?

**Comment by DiggaTheWolf** [comment]
I think that would do it, allowing copy of all or selected rows and please include the column headers too.

**Comment by MscrmTools** [comment]
Ok, Excel export is now possible
