### ISSUE TITLE
Error when i try to load entity informations / exeption related to the last update ? 

### ISSUE THREAD

**Issue by Powerana** [MscrmTools/MsCrmTools.MetadataBrowser#20]
System.ArgumentOutOfRangeException: L'index 0 est hors limites.
Nom du paramètre : index
   à System.Windows.Forms.Control.ControlCollection.get_Item(Int32 index)
   à MsCrmTools.MetadataBrowser.MainControl.<>c__DisplayClass22_0.<LoadEntity>b__1(RunWorkerCompletedEventArgs e)
   à XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   à System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by MscrmTools** [comment]
What is the version of the targeted environment/organization?

**Comment by Powerana** [comment]
Env Version : 9.1.0000.16541

**Comment by MscrmTools** [comment]
I will check my version but did not have any issue with the online env I worked with today

**Comment by AntonUdalow** [comment]
I have this issue also, after I have reset attribute columns:
System.ArgumentOutOfRangeException: Der Index 0 liegt außerhalb des Bereichs.
Parametername: index
   bei System.Windows.Forms.Control.ControlCollection.get_Item(Int32 index)
   bei MsCrmTools.MetadataBrowser.MainControl.mainTabControl_SelectedIndexChanged(Object sender, EventArgs e)
   bei System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   bei System.Windows.Forms.TabControl.WmSelChange()
   bei System.Windows.Forms.TabControl.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I make reset because I have another issue after update (field not found):
System.MissingFieldException: Feld nicht gefunden: "Microsoft.Xrm.Sdk.Metadata.AttributeTypeDisplayName.FileType".
   bei MsCrmTools.MetadataBrowser.UserControls.EntityPropertiesControl.LoadAttributes(IEnumerable`1 attributes, String filter)
   bei MsCrmTools.MetadataBrowser.UserControls.EntityPropertiesControl.RefreshContent(EntityMetadata newEmd)
   bei MsCrmTools.MetadataBrowser.MainControl.<>c__DisplayClass22_0.<LoadEntity>b__1(RunWorkerCompletedEventArgs e)
   bei XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   bei System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by MscrmTools** [comment]
@AntonUdalow What is your CRM/D365/CDS target version?

**Comment by MscrmTools** [comment]
@Powerana , @AntonUdalow  Could you test with this version? That should fix both of your issues
[MsCrmTools.MetadataBrowser.zip](https://github.com/MscrmTools/MsCrmTools.MetadataBrowser/files/4728680/MsCrmTools.MetadataBrowser.zip)
